# Generated by Django 3.2.10 on 2022-04-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
