# Generated by Django 3.2.10 on 2022-04-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_awards', '0002_auto_20220412_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='owner',
            new_name='user',
        ),
    ]
