# Generated by Django 3.2.10 on 2022-04-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_awards', '0005_rename_owner_rate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
